name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15ad4b8755f098d6da8dcac54df8bd31facdbd8c21d22d13302e96b7553031db"

[versions]
fabric = "0.19.2"
minecraft = "1.21.4"
