name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "810aca7acf50c7e9c2580b85a1f5a55d06621ef78cb37eeeada4bec131afb296"

[versions]
fabric = "0.19.2"
minecraft = "1.21.4"
