name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4042bff880cbcfa74eff91ce16b07dd50623e22ac4d86e1e686660354fcedf98"

[versions]
fabric = "0.19.2"
minecraft = "1.21.4"
