name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39aaef73390644b14d3d487f2b9e5133eff5ba8a071a4bd69a40d356541cae9"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
