name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f7009e381a991206e6316c79d0f555d9d8666b61f3002f9870cb5b012aa7623"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
