name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7f92e9bd3757adfb924ce193e9c06bcfe87a601bbe7d8f92a7dc7a0bd229e6e"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
