name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57ea6f87c29d16fe29d42ccebd96fb23d032b20fee410856c2c62bcdd7ebb56c"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
