name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9527aa7a00730933306b57a8d78390db7200c8ca5fd1ab47bf09cabe9f8d03c"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
