name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b496cafcaa7d5beba91706a2e2eaf038d72cf843331ed4d83e04b00e187c2516"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
