name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8f26af995a3d4435f2002f70b5a7bc0df5140f9a28838d3440dc721e0d7752c"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
