name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a6846e731da7cdfa2df429a91fae5121c0b3a82b595a8eec92a9218b2624192"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
