name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52dafdd19c6ef7a72dcffb580070fc1bd9f22c5577a9cd5d35f53f88bdfcb60c"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
