name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c4c79563c7e9a674f6d6552f73c242c09d7e4db71686269435b54f0e5f42830"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
