name = "Keep It Simple"
author = "MisterVitoPro"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ff0d33e994a664279fd0df4f05fead739d7e8d093bcabcf8c1e06db01e64b4f"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
